name: Windows tests

#on: [push]
on: [workflow_dispatch] #Manually
#on:
#  workflow_run:
#    workflows: ["Build"]
#    types:
#      - completed

jobs:
  tests:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - name: Build a wheel via an sdist
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build
        pip install dist/pyxai-1.0.7-cp311-cp311-win_amd64.whl
      #sudo apt install ffmpeg libsm6 libxext6 qt6-base-dev libxcb-cursor0 -y
    - name: Run test suite
      run: |
        python3 -m pyxai -tests